### ISSUE TITLE
Prepare Figma Prototype of the App

### ISSUE THREAD

**Issue by abhiraj-mengade** [Neumannics/5miles#1]

**Comment by pranav2305** [comment]
@Amanshenoy008 Please share the link of the figma once you start working on it so that we can give our inputs as well. Also move the task to In Progress once you start

**Comment by ShenoyAman** [comment]
https://www.figma.com/file/EQczs7PdOcbsFe9vNHsd4s/5Miles-UI-design?node-id=0%3A1&t=TLYPMa1Igq5fGC2H-1
